### ISSUE TITLE
Table ID as part of the table_view_builder

### ISSUE THREAD

**Issue by tmnyoni** [alecmus/lecui#7]
I have a suggestion that if possible, add a table ID. The ID does not change when the user sorts the table. And the programmer can either choose to include it or not. I think it would be an amazing feature.

**Comment by alecmus** [comment]
Thanks for the suggestion @tmnyoni . The enhancement has now been added. Kindly refer to 4511a26f9a3eaf92bf95ac492ad354a27bc8789d.
